#!/bin/bash

# Run wal 
echo "Running wal"
if [ $# -eq 0 ] 
	then # if no args, default to current wallpaper dir
		wal -q --backend colorz -i /home/scrawl/Pictures/Wallpapers/Current -n && echo "Defaulting to ~/Pictures/Wallpapers/Current"
        DISPLAY=:0 feh --bg-fill "$(< "/home/scrawl/.cache/wal/wal")"
		notify-send "Wallpaper changed" "~/Pictures/Wallpapers/Current/"
	else # otherwise take arg
		wal -q --backend colorz -i $1 -n && echo "Setting wallpaper to $1"
        DISPLAY=:0 feh --bg-fill "$(< "/home/scrawl/.cache/wal/wal")"
		notify-send "Wallpaper changed" "$1"
        
fi
wal --preview
echo "Wal finished"

